 

---
--- CRIAÇÃO DE TABELA 
---
CREATE TABLE TB_CLIENTE
( ID_CLIENTE     NUMBER(10)
, NOME           VARCHAR2(200) NOT NULL
, EMAIL          VARCHAR2(100) NOT NULL
, CEP            NUMBER(8) 
, LOGRADOURO     VARCHAR2(100)
, NUMERO         NUMBER(5)
, BAIRRO         VARCHAR2(100 )
, CIDADE         VARCHAR2(100)
, UF             VARCHAR2(2)
, ATIVO          NUMBER(1) NOT NULL
, DT_CRIACAO     DATE      NOT NULL
, DT_ATUALIZACAO DATE
); 

ALTER TABLE TB_CLIENTE ADD ( CONSTRAINT CLIENTE_PK PRIMARY KEY ( ID_CLIENTE )
USING INDEX
)
/

ALTER TABLE TB_CLIENTE ADD (CONSTRAINT CLIENTE2_UK UNIQUE (EMAIL) )
/

ALTER TABLE TB_CLIENTE ADD (CONSTRAINT CLIENTE3_CHK CHECK (UF IN ('AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO' )))
/

CREATE SEQUENCE CLIENTE_SEQ
NOMAXVALUE
NOMINVALUE
NOCYCLE
NOCACHE
/